# Generated by Django 4.2 on 2023-04-23 17:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dateplan", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("searchDate", models.DateField()),
                ("planDate", models.DateField()),
                ("num", models.IntegerField()),
                ("temperature", models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name="APICall",
        ),
    ]
