# Generated by Django 4.2 on 2023-04-24 01:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dateplan", "0003_plancontext_delete_userresult"),
    ]

    operations = [
        migrations.AddField(
            model_name="plancontext",
            name="plan_date",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 4, 23, 12, 0, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
    ]
